package io.radanalytics.tutorial.scala.drools.rules;

import io.radanalytics.tutorial.scala.drools.model.Input;
import io.radanalytics.tutorial.scala.drools.model.Output;

rule "Turn Inputs into Outputs"
    when
        Input( $value : value )
        accumulate( Input( value == $value ), $count : count() )
        not Output( value == $value )
    then
        insert( new Output( $value, $count ) );
end